version: "2"
services:
  web:
    build: .
    image: ctftraining/base_image_nginx_mysql_php_73
    ports:
      - "127.0.0.1:8085:80"
    environment:
      - ROOT_PASSWORD=
      - AWD_PASSWORD=
      - FLAG=CTFTraining{nginx_mysql_php_73}
      - FLAG_TABLE=flagtable
      - FLAG_COLUMN=flagcolumn