version: "2"
services:
  web:
    build: .
    image: sonder39/cssec-lnmps
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:22:22"
      - "127.0.0.1:9000:9000"
    environment:
      - ROOT_PASSWORD=root
      - AWD_PASSWORD=awd
      - FLAG=CTFTraining{nginx_mysql_php_73}
      - FLAG_TABLE=flagtable
      - FLAG_COLUMN=flagcolumn
