#!/bin/sh

echo "=> Setting system root password ..."
if [ "$ROOT_PASSWORD" = "" ]; then
    ROOT_PASSWORD=root
fi
echo "root:$ROOT_PASSWORD" | chpasswd
echo "===> System root password set to $ROOT_PASSWORD!"

echo "=> Setting AWD password ..."
if [ "$AWD_PASSWORD" = "" ]; then
    AWD_PASSWORD=awd
fi
echo "awd:$AWD_PASSWORD" | chpasswd
echo "===> AWD password set to $AWD_PASSWORD!"
/usr/sbin/sshd 
echo "SSH service started with exit code $?"

mysqld_safe &

mysql_ready() {
	mysqladmin ping --socket=/run/mysqld/mysqld.sock --user=root --password=root > /dev/null 2>&1
}

while !(mysql_ready)
do
	echo "waiting for mysql ..."
	sleep 3
done

if [[ -f /run.sh ]]; then
	source /run.sh
fi

if [[ -f /var/www/html/db.sql ]]; then
    mysql -e "source /var/www/html/db.sql" -uroot -proot
    rm -f /var/www/html/db.sql
fi

php-fpm &

nginx &

tail -F /dev/null
