#!/bin/sh

# Generate a password for the user 'newuser' and print it
PASSWD=$(pwgen -ys 15 1)
echo "awd:$PASSWD" | chpasswd
echo "The password for user:awd is $PASSWD"
/usr/sbin/sshd 
echo "SSH service started with exit code $?"

mysqld_safe &

mysql_ready() {
	mysqladmin ping --socket=/run/mysqld/mysqld.sock --user=root --password=root > /dev/null 2>&1
}

while !(mysql_ready)
do
	echo "waiting for mysql ..."
	sleep 3
done

if [[ -f /flag.sh ]]; then
	source /flag.sh
fi

if [[ -f /var/www/html/db.sql ]]; then
    mysql -e "source /var/www/html/db.sql" -uroot -proot
    rm -f /var/www/html/db.sql
fi

php-fpm &

nginx &

tail -F /dev/null
